//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public interface ICacheable
	{
		/// <summary>
		/// Gets the cache category.
		/// </summary>
		string GetCacheCategory();

		/// <summary>
		/// Frees the item from cache.
		/// </summary>
		void FreeItem();

		/// <summary>
		/// Determines wether the item is free
		/// </summary>
    bool IsFree();

		/// <summary>
		/// Sets the free state to bool
		/// </summary>
    void SetFree(bool free);
	}
}
